services:
  web:
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
      - 80:80
    volumes:
      - ./poke-buds-docker-angular:/project
      - /project/node_modules
