# syntax=docker/dockerfile:1.4

# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM --platform=$BUILDPLATFORM node:17.0.1-bullseye-slim as builder

# Set the working directory
RUN mkdir /project
WORKDIR /project

# Install all the dependencies
RUN npm install -g @angular/cli@latest

COPY package.json package-lock.json ./
RUN npm ci

# Add the source code to app
COPY . .
CMD ["ng", "serve", "--host", "0.0.0.0"]

FROM builder as dev-envs

RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF
# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /

CMD ["ng", "serve", "--host", "0.0.0.0"]
